config/routes.rb
Rails.application.routes.draw do
  resources :cmments
  resources :post1s
  resources :posts
  resources :students
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cmment.rb
class Cmment < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/post1.rb
class Post1 < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cmments_controller.rb
class CmmentsController < ApplicationController
  before_action :set_cmment, only: %i[ show edit update destroy ]

  # GET /cmments or /cmments.json
  def index
    @cmments = Cmment.all
  end

  # GET /cmments/1 or /cmments/1.json
  def show
  end

  # GET /cmments/new
  def new
    @cmment = Cmment.new
  end

  # GET /cmments/1/edit
  def edit
  end

  # POST /cmments or /cmments.json
  def create
    @cmment = Cmment.new(cmment_params)

    respond_to do |format|
      if @cmment.save
        format.html { redirect_to cmment_url(@cmment), notice: "Cmment was successfully created." }
        format.json { render :show, status: :created, location: @cmment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cmment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cmments/1 or /cmments/1.json
  def update
    respond_to do |format|
      if @cmment.update(cmment_params)
        format.html { redirect_to cmment_url(@cmment), notice: "Cmment was successfully updated." }
        format.json { render :show, status: :ok, location: @cmment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cmment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cmments/1 or /cmments/1.json
  def destroy
    @cmment.destroy

    respond_to do |format|
      format.html { redirect_to cmments_url, notice: "Cmment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cmment
      @cmment = Cmment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cmment_params
      params.require(:cmment).permit(:name3, :stream3)
    end
end

app/controllers/post1s_controller.rb
class Post1sController < ApplicationController
  before_action :set_post1, only: %i[ show edit update destroy ]

  # GET /post1s or /post1s.json
  def index
    @post1s = Post1.all
  end

  # GET /post1s/1 or /post1s/1.json
  def show
  end

  # GET /post1s/new
  def new
    @post1 = Post1.new
  end

  # GET /post1s/1/edit
  def edit
  end

  # POST /post1s or /post1s.json
  def create
    @post1 = Post1.new(post1_params)

    respond_to do |format|
      if @post1.save
        format.html { redirect_to post1_url(@post1), notice: "Post1 was successfully created." }
        format.json { render :show, status: :created, location: @post1 }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post1.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post1s/1 or /post1s/1.json
  def update
    respond_to do |format|
      if @post1.update(post1_params)
        format.html { redirect_to post1_url(@post1), notice: "Post1 was successfully updated." }
        format.json { render :show, status: :ok, location: @post1 }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post1.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post1s/1 or /post1s/1.json
  def destroy
    @post1.destroy

    respond_to do |format|
      format.html { redirect_to post1s_url, notice: "Post1 was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post1
      @post1 = Post1.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post1_params
      params.require(:post1).permit(:name2, :stream2)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:name2, :stream2)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :stream)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cmments_helper.rb
module CmmentsHelper
end

app/helpers/post1s_helper.rb
module Post1sHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/cmments/_cmment.html.erb
<div id="<%= dom_id cmment %>">
  <p>
    <strong>Name3:</strong>
    <%= cmment.name3 %>
  </p>

  <p>
    <strong>Stream3:</strong>
    <%= cmment.stream3 %>
  </p>

</div>

app/views/cmments/_form.html.erb
<%= form_with(model: cmment) do |form| %>
  <% if cmment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cmment.errors.count, "error") %> prohibited this cmment from being saved:</h2>

      <ul>
        <% cmment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name3, style: "display: block" %>
    <%= form.text_field :name3 %>
  </div>

  <div>
    <%= form.label :stream3, style: "display: block" %>
    <%= form.text_field :stream3 %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cmments/edit.html.erb
<h1>Editing cmment</h1>

<%= render "form", cmment: @cmment %>

<br>

<div>
  <%= link_to "Show this cmment", @cmment %> |
  <%= link_to "Back to cmments", cmments_path %>
</div>

app/views/cmments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cmments</h1>

<div id="cmments">
  <% @cmments.each do |cmment| %>
    <%= render cmment %>
    <p>
      <%= link_to "Show this cmment", cmment %>
    </p>
  <% end %>
</div>

<%= link_to "New cmment", new_cmment_path %>

app/views/cmments/new.html.erb
<h1>New cmment</h1>

<%= render "form", cmment: @cmment %>

<br>

<div>
  <%= link_to "Back to cmments", cmments_path %>
</div>

app/views/cmments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cmment %>

<div>
  <%= link_to "Edit this cmment", edit_cmment_path(@cmment) %> |
  <%= link_to "Back to cmments", cmments_path %>

  <%= button_to "Destroy this cmment", @cmment, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rrrr</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/post1s/_form.html.erb
<%= form_with(model: post1) do |form| %>
  <% if post1.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post1.errors.count, "error") %> prohibited this post1 from being saved:</h2>

      <ul>
        <% post1.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name2, style: "display: block" %>
    <%= form.text_field :name2 %>
  </div>

  <div>
    <%= form.label :stream2, style: "display: block" %>
    <%= form.text_field :stream2 %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/post1s/_post1.html.erb
<div id="<%= dom_id post1 %>">
  <p>
    <strong>Name2:</strong>
    <%= post1.name2 %>
  </p>

  <p>
    <strong>Stream2:</strong>
    <%= post1.stream2 %>
  </p>

</div>

app/views/post1s/edit.html.erb
<h1>Editing post1</h1>

<%= render "form", post1: @post1 %>

<br>

<div>
  <%= link_to "Show this post1", @post1 %> |
  <%= link_to "Back to post1s", post1s_path %>
</div>

app/views/post1s/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Post1s</h1>

<div id="post1s">
  <% @post1s.each do |post1| %>
    <%= render post1 %>
    <p>
      <%= link_to "Show this post1", post1 %>
    </p>
  <% end %>
</div>

<%= link_to "New post1", new_post1_path %>

app/views/post1s/new.html.erb
<h1>New post1</h1>

<%= render "form", post1: @post1 %>

<br>

<div>
  <%= link_to "Back to post1s", post1s_path %>
</div>

app/views/post1s/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post1 %>

<div>
  <%= link_to "Edit this post1", edit_post1_path(@post1) %> |
  <%= link_to "Back to post1s", post1s_path %>

  <%= button_to "Destroy this post1", @post1, method: :delete %>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name2, style: "display: block" %>
    <%= form.text_field :name2 %>
  </div>

  <div>
    <%= form.label :stream2, style: "display: block" %>
    <%= form.text_field :stream2 %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Name2:</strong>
    <%= post.name2 %>
  </p>

  <p>
    <strong>Stream2:</strong>
    <%= post.stream2 %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :stream, style: "display: block" %>
    <%= form.text_field :stream %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>Name:</strong>
    <%= student.name %>
  </p>

  <p>
    <strong>Stream:</strong>
    <%= student.stream %>
  </p>

</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students</h1>

<div id="students">
  <% @students.each do |student| %>
    <%= render student %>
    <p>
      <%= link_to "Show this student", student %>
    </p>
  <% end %>
</div>

<%= link_to "New student", new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>